version: "3.8"
services:
  filebrowser:
    image: jims2025-bot/filebrowserquantum:v3.0.1-jimmeta.1
    container_name: FBQuantum_JimMeta
    networks:
      shared_bridge:
        ipv4_address: 172.22.0.101
    ports:
      - "3671:80"
    volumes:
      # Your photo library
      - /srv/dev-disk-by-uuid-90be2239-3de1-4f60-a6f1-a1f95cd93876/PERSONAL-CRYPT/PHOTOS/zScannedAlbums:/srv
    environment:
      - FB_BASEURL=/albums
      - FB_ROOT=/srv
    restart: unless-stopped

networks:
  shared_bridge:
    external: true
    name: shared_bridge
